#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnetfilter_cthelper
Version  : 1.0.0
Release  : 5
URL      : http://www.netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2
Source0  : http://www.netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2
Summary  : Netfilter user-space helper infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_cthelper-lib
BuildRequires : pkgconfig(libmnl)

%description
= nfnl_cthelper: User-space infrastructure for connection tracking helpers =
Author: Pablo Neira Ayuso <pablo@netfilter.org>

%package dev
Summary: dev components for the libnetfilter_cthelper package.
Group: Development
Requires: libnetfilter_cthelper-lib

%description dev
dev components for the libnetfilter_cthelper package.


%package lib
Summary: lib components for the libnetfilter_cthelper package.
Group: Libraries

%description lib
lib components for the libnetfilter_cthelper package.


%prep
%setup -q -n libnetfilter_cthelper-1.0.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_cthelper/libnetfilter_cthelper.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
