#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA4111F89BB5F58CC (coreteam@netfilter.org)
#
Name     : libnetfilter_cthelper
Version  : 1.0.0
Release  : 10
URL      : http://www.netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2
Source0  : http://www.netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2
Source1  : http://www.netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2.sig
Summary  : Netfilter user-space helper infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_cthelper-lib = %{version}-%{release}
Requires: libnetfilter_cthelper-license = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)

%description
= nfnl_cthelper: User-space infrastructure for connection tracking helpers =
Author: Pablo Neira Ayuso <pablo@netfilter.org>

%package dev
Summary: dev components for the libnetfilter_cthelper package.
Group: Development
Requires: libnetfilter_cthelper-lib = %{version}-%{release}
Provides: libnetfilter_cthelper-devel = %{version}-%{release}
Requires: libnetfilter_cthelper = %{version}-%{release}

%description dev
dev components for the libnetfilter_cthelper package.


%package lib
Summary: lib components for the libnetfilter_cthelper package.
Group: Libraries
Requires: libnetfilter_cthelper-license = %{version}-%{release}

%description lib
lib components for the libnetfilter_cthelper package.


%package license
Summary: license components for the libnetfilter_cthelper package.
Group: Default

%description license
license components for the libnetfilter_cthelper package.


%prep
%setup -q -n libnetfilter_cthelper-1.0.0
cd %{_builddir}/libnetfilter_cthelper-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1593109620
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1593109620
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libnetfilter_cthelper
cp %{_builddir}/libnetfilter_cthelper-1.0.0/COPYING %{buildroot}/usr/share/package-licenses/libnetfilter_cthelper/075d599585584bb0e4b526f5c40cb6b17e0da35a
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_cthelper/libnetfilter_cthelper.h
/usr/lib64/libnetfilter_cthelper.so
/usr/lib64/pkgconfig/libnetfilter_cthelper.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetfilter_cthelper.so.0
/usr/lib64/libnetfilter_cthelper.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnetfilter_cthelper/075d599585584bb0e4b526f5c40cb6b17e0da35a
